server:
  port: 8080

spring:
  profiles:
    active: dev

security:
  jwt:
    secret_key: ${SECRET_KEY:4eeab38d706831be4b36612ead768ef8182d1dd6f0e14e5dc934652e297fb16a}
    access_token_expiration: ${ACCESS_TOKEN_EXPIRATION:36000000}
    refresh_token_expiration: ${REFRESH_TOKEN_EXPIRATION:252000000}


---
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:postgresql://localhost:5432/reservation_info
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:MaL8033038}
    driver-class-name: org.postgresql.Driver

    hikari:
      connection-timeout: 20000
      minimum-idle: 5
      maximum-pool-size: 12
      idle-timeout: 300000
      max-lifetime: 1200000
      pool-name: ReservationInfoPool

  main:
    allow-bean-definition-overriding: true

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

    hibernate:
      ddl-auto: update

    show-sql: true

logging:
  level:
    com.example.app: DEBUG
    org.springframework.security: DEBUG


---
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:postgresql://database:5432/reservation_info
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

    hikari:
      connection-timeout: 20000
      minimum-idle: 5
      maximum-pool-size: 12
      idle-timeout: 300000
      max-lifetime: 1200000
      pool-name: ReservationInfoPool

  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

    hibernate:
      ddl-auto: validate

    show-sql: false

logging:
  level:
    com.example.app: INFO